GET http://localhost:3000/


#####
POST http://localhost:3011/api/users
Content-Type: application/json

{
    "name": "Bobx",
    "age": 1,
    "password": "tesxasdgasd",
    "email": "gaszgsdaxzzzzxx@fgasd.com"
}
#####
GET http://localhost:3011/api/user/61bf2c6529df86101a326739
